#!/usr/bin/env node
/**
 * Phase 25 — launchd plist generator.
 *
 * Reads launchd/jobs.json and writes one launchd/plists/<name>.plist
 * file per job. Run after editing jobs.json:
 *
 *   node launchd/generate-plists.js
 *
 * Each generated plist has three placeholder fields you must replace
 * once on each Mac install (the install.sh script does this for you):
 *   - REPLACE_ME_ABSOLUTE_PATH_TO_REPO
 *   - REPLACE_ME_ABSOLUTE_PATH_TO_NODE
 *   - REPLACE_ME_USERNAME
 *
 * The install.sh script substitutes these in-place via `sed` so you
 * never edit XML by hand.
 *
 * This script has zero dependencies — pure Node + fs.
 */

const fs = require('fs')
const path = require('path')

const HERE = __dirname
const JOBS_FILE = path.join(HERE, 'jobs.json')
const PLISTS_DIR = path.join(HERE, 'plists')

if (!fs.existsSync(JOBS_FILE)) {
  console.error(`[generate-plists] ${JOBS_FILE} not found`)
  process.exit(1)
}

const config = JSON.parse(fs.readFileSync(JOBS_FILE, 'utf-8'))
if (!Array.isArray(config.jobs)) {
  console.error('[generate-plists] jobs.json must contain a "jobs" array')
  process.exit(1)
}

if (!fs.existsSync(PLISTS_DIR)) {
  fs.mkdirSync(PLISTS_DIR, { recursive: true })
}

function escapeXml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function scheduleBlock(schedule) {
  if (schedule.interval != null) {
    return `  <key>StartInterval</key>\n  <integer>${schedule.interval}</integer>`
  }
  if (schedule.calendar) {
    const c = schedule.calendar
    const parts = []
    if (c.Hour != null) parts.push(`    <key>Hour</key><integer>${c.Hour}</integer>`)
    if (c.Minute != null) parts.push(`    <key>Minute</key><integer>${c.Minute}</integer>`)
    if (c.Weekday != null) parts.push(`    <key>Weekday</key><integer>${c.Weekday}</integer>`)
    return `  <key>StartCalendarInterval</key>\n  <dict>\n${parts.join('\n')}\n  </dict>`
  }
  throw new Error('schedule must specify either interval or calendar')
}

function plistFor(job) {
  const label = `com.agrisafe.${job.name}`
  const sched = scheduleBlock(job.schedule)
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  ${escapeXml(job.description || job.name)}
  ${job.comment ? `(${escapeXml(job.comment)})` : ''}

  Generated by launchd/generate-plists.js from launchd/jobs.json.
  DO NOT EDIT BY HAND — re-run the generator.

  The three REPLACE_ME placeholders are filled in by launchd/install.sh
  when you install on the Mac.
-->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>

  <key>WorkingDirectory</key>
  <string>REPLACE_ME_ABSOLUTE_PATH_TO_REPO</string>

  <key>ProgramArguments</key>
  <array>
    <string>REPLACE_ME_ABSOLUTE_PATH_TO_NODE</string>
    <string>--env-file=.env.local</string>
    <string>node_modules/.bin/tsx</string>
    <string>src/scripts/cron/run-job.ts</string>
    <string>${escapeXml(job.name)}</string>
  </array>

${sched}

  <key>RunAtLoad</key>
  <false/>

  <key>StandardOutPath</key>
  <string>/Users/REPLACE_ME_USERNAME/Library/Logs/AgriSafe/${escapeXml(job.name)}.log</string>
  <key>StandardErrorPath</key>
  <string>/Users/REPLACE_ME_USERNAME/Library/Logs/AgriSafe/${escapeXml(job.name)}.log</string>

  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>

  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
`
}

let written = 0
for (const job of config.jobs) {
  if (!job.name || !job.schedule) {
    console.error(`[generate-plists] skipping malformed entry: ${JSON.stringify(job)}`)
    continue
  }
  const xml = plistFor(job)
  const file = path.join(PLISTS_DIR, `com.agrisafe.${job.name}.plist`)
  fs.writeFileSync(file, xml)
  written++
}

console.log(`[generate-plists] wrote ${written} plist file(s) to ${PLISTS_DIR}`)
